### ISSUE TITLE
Contact us fixes

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#373] opened 2023-11-16 11:40 UTC
<img width="847" alt="Screenshot 2023-11-16 at 12 40 05" src="https://github.com/hlxsites/bevespi/assets/111385/25cb1c21-2bf0-49ce-bdcd-088e2aab6348">

**Comment by lansami** [comment] 2023-11-16 14:45
Reopening the issue because point c is not fixed, reproducible only with an iphone

**Comment by lansami** [comment] 2023-11-16 15:12
closed, issue fixed by https://github.com/hlxsites/bevespi/pull/378

**Closed** 2023-11-16 15:11 UTC
Labels: UI
